### ISSUE TITLE
In VS Extensions gallery, it displayed that the PoshTools is installed, but there is a link "Install Now" in the InfoBar leading you to install PoshTools 

### ISSUE THREAD

**Issue by v-hedli** [microsoft/poshtools#536] opened 2015-05-14 10:14 UTC
Repro Steps:
1. Open Dev14 without installing PoshTools
2. Open a PS file
3. There is a link "Install Now" in InfoBar which will lead you to install PowerShell Tools for Visual Studio.
4. Open Tools->Extensions and Updates... windows and search the PowerShell Tools for Visual Studio
5. Verify PowerShell Tools for Visual Studio status.

Expected:
PowerShell Tools for Visual Studio is not installed.

Actual:
It displayed PowerShell Tools for Visual Studio is already installed. Please see below screenshot:

![installnow](https://cloud.githubusercontent.com/assets/12443209/7629932/8db49642-fa63-11e4-8b6e-93fdd7e4b0b5.png)

**Comment by ASayre** [comment] 2015-05-18 06:50
Currently by design...ish; A v0.1 is installed, so that way users are notified that it exists.  I'm Okay with 'wont-fixing' this currently.

@bmoore-msft @jinglou-  Thoughts?

**Comment by bmoore-msft** [comment] 2015-05-18 15:05
from the bmp I can't tell what version was installed, but if it is an earlier version, then yes - by design.  The gold bar link will go to the gallery, not the dlg so that should help direct users.

**Comment by ASayre** [comment] 2015-05-18 16:45
@bmoore-msft The version installed was the 0.1 'dummy' VSIX :)  Closing this out then.  @v-hedli Please reopen if you disagree!

**Closed as completed** 2015-05-18 16:45 UTC
