### ISSUE TITLE
REPL doesn't work after run cmd for many times

### ISSUE THREAD

**Issue by ghost** [microsoft/poshtools#576] opened 2015-05-22 10:15 UTC
Powershell V4 + latest PoshTool from http://aka.ms/Get-PoshToolsNightly

Repro Steps:
1. Open REPL window
2. Run a cmd many times. Like Write-Output "test"

Expect: Could run cmd successful.
Actual: 
Throw error: There is a problem in the powershell host service. If you then run other cmd will said: The communication object, System.ServiceModel.Channels.ServiceChannel, cannot be used for communication because it has been Aborted.

More Info:
Unstable repro this issue. Could repro in Dev12 and Dev14
Repro machine: 
Name/IP: CT00139/10.226.89.75
User: Redmond/vslab2
![repl](https://cloud.githubusercontent.com/assets/12426589/7768525/80b65830-00ae-11e5-80ba-ee171ba0111e.png)

**Comment by ericdevg** [comment] 2015-05-22 17:27
Thanks for reporting this issue @ArcherSui , I think we've already tracked down this root cause of this issue, there are various of repro for this issue, and very few of them ends up consistent. I'll try to make fix today, and let us try verify it after I merged my fix. Will let you know.

**Comment by ASayre** [comment] 2015-05-29 16:23
@ArcherSui We believe we've fixed this, and are closing it out as such!  Please reopen if you still encounter this!

**Closed as completed by ASayre** 2015-05-29 16:23 UTC
Labels: bug
