### ISSUE TITLE
REPL window is eating confirmation prompts

### ISSUE THREAD

**Issue by bmoore-msft** [microsoft/poshtools#490] opened 2015-04-28 20:34 UTC
the repl window is eating confirmation prompts.

c:>md foo
c:>rd foo -confirm

You won't get a prompt.  This also happens with -Force params which can be pretty destructive.

**Comment by ASayre** [comment] 2015-04-28 21:17
Dupe of https://github.com/adamdriscoll/poshtools/issues/120 ?  Given the lack of prompt for these types of, I think we should bump up the priority :)

**Closed as completed** 2015-06-15 20:36 UTC
Labels: bug
