### ISSUE TITLE
Typing two intellisense triggering character fast will cause completion list not showing up

### ISSUE THREAD

**Issue by HuanhuanSunMSFT** [microsoft/poshtools#237] opened 2015-03-12 03:02 UTC
Type in a normal speed:
Write-Host "C:\
Expected: It should show the completion list. 
Actual: No completion list shows though status bar indicates it seems having triggered IntelliSense

**Comment by ASayre** [comment] 2015-03-13 22:36
Potential same root cause as #109?

**Comment by HuanhuanSunMSFT** [comment] 2015-04-01 21:25
This one should have been covered in racing condition fix. @AndreSayreMSFT @EricMSFT

**Comment by ASayre** [comment] 2015-04-01 21:35
Agreed.  Closing this out.

**Closed as completed by ASayre** 2015-04-01 21:35 UTC
Labels: bug, 64-bit Intellisense
