### ISSUE TITLE
Exception occured while typing in the editor

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/poshtools#312] opened 2015-03-26 22:27 UTC
- Create a PS script project
- In the editor, type the following:
  `([wmiSearcher]@'SELECT * FROM CIM_Job WHERE Priority > 1'@).g`
- This has caused VS to crash.  

The CmdLet I was trying to type was:
`([wmiSearcher]@'SELECT * FROM CIM_Job WHERE Priority > 1'@).get() | Format-Custom`

Here is the callstack:
`System.IndexOutOfRangeException: Index was outside the bounds of the array.&#x000D;&#x000A;   at PowerShellTools.Intellisense.PowerShellCompletionSet.SelectBestMatch()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Match()&#x000D;&#x000A;   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.OnViewBuffer_Changed(Object sender, TextContentChangedEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.RaiseEvent[TArgs](Object sender, EventHandler`1 eventHandlers, TArgs args)`

**Comment by jinglouMSFT** [comment] 2015-03-27 01:16
class MyClass
{
    [UInt32] $Size;
    [String] $Name;
    MyClass([UInt32] $NewSize, [String] $NewName) {
        #Set the size
    $Size = $NewSize;
        #Set the name
    $Name = $NewName;  
    }

```
MyClass([UInt32] $NewSize = 0, [String] $NewName = 'MyClass') {}

[void] Drink([UInt32] $Amount) {
    $Size = $Size - $Amount;
}
```

}

$MyBeer = [MyClass]::n
when instantiating MyClass also caused an exception. It happened when typing 'new'.

**Comment by ASayre** [comment] 2015-03-30 18:07
Dupe of #305

**Comment by HuanhuanSunMSFT** [comment] 2015-03-30 20:52
Fixed

**Closed as completed by HuanhuanSunMSFT** 2015-03-30 20:52 UTC
Labels: bug, BugBash
