### ISSUE TITLE
we should error if there is nothing after the pipeline then hit enter, 

### ISSUE THREAD

**Issue by jinglouMSFT** [microsoft/poshtools#309] opened 2015-03-26 21:39 UTC
This is the example of what I am expecting:
```Get-ChildItem 'c:\users' -Recurse | 

> >  where { -not $_.PSIsContainer -and $_.Extension -match 'wma | mp3'} | 
> >  Measure-Object -property length -sum -min -max -ave```

Two issues:
1). After I hit <enter> after the pipeline on first line, I am not getting the prompt on the 2nd line or 3rd line.  We return to normal PS command prompt (in the REPL windows).  eg:

`PS C:\> Get-ChildItem 'c:\users\jinglou' -Recurse | 
PS C:\>`

2). We do get a red squiggle after the pipeline, and the message says "An empty pipe element is not allowed". Andre feels we should have an error message.

**Comment by ASayre** [comment] 2015-03-26 23:33
Dupe of #200 ?

**Comment by ASayre** [comment] 2015-03-27 22:37
Dupe

**Closed as completed by ASayre** 2015-03-27 22:37 UTC
Labels: bug, duplicate, BugBash
